<a href="https://colab.research.google.com/github/htapiagroup/introduccion-a-numpy-JosueJuarez/blob/master/Introducci%C3%B3n_a_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introducción a Numpy
##Josué Juárez Morales
-----

In [0]:
import numpy as np

#Tipos de datos en python

## Listas en Python 

Una lista es una estructura de datos que permite colectar objetos. 
Creamos una lista de enteros de la siguiente forma:

In [0]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
type(L[0])

int

O una lista de caracteres de texto:

In [0]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [0]:
type(L2[0])

str

Gracias al tipado dinámico podemos crear listas heterogéneas:

In [0]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Arreglos de Tipo Fijo en Python

- En Python hay diferentes opciones para guardar datos en buffers de tipo fijo
- El modulo interno ``array`` (disponible a partir de Python 3.3) sirve para crear arreglos densos de tipo uniforme:

In [0]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Aquí ``'i'`` indica que las entradas son enteros.
- El objeto ``ndarray`` de la libreria NumPy  es mucho mas útil ya que implementa operaciones sobre los datos contenidos.
- Antes de explorar estas operaciones, veamos diversas maneras de crear arreglos de NumPy
- Comenzamos con la manera standard de importar NumPy, usando el alias ``np``:

## Crear Arreglos a partir de Listas de Python

Podemos usar ``np.array`` para crear arreglos a partir de listas:

In [0]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

- A diferencia de las lista en Python, NumPy está restringif a arreglos que contienen el mismo tipo de datos
- Si los tipos no coinciden NumPy trata de ajustar (*upcast*, emitir) si es posible
- En el siguiente ejemplo, los enteros se emiten a punto flotante:

In [0]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

- Podemos indicar el tipo de datos del arreglo explicitamente usando la palabra ``dtype``:

In [0]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

- A diferencia de las listas, los arreglos de NumPy pueden ser explicitamente multi-dimensionales
- A continuación, una forma de inicializar un arreglo multidimensional usando una lista de listas:

In [0]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

- Las listas interiores se toman como renglones del arreglo bidimensional resultante

## Creando Arreglos 

- Para arreglos grandes, es mas eficiente crearlos usando rutinas implementadas en NumPy:

In [4]:
# Crea arreglo de enteros de longitud-10 lleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Crea arreglo con puntos flotantes de dimensiones 3x5 (3 renglones, 5 columnas) lleno de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Crea arreglo de 3x5 array lleno de 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Crea arreglo lleno con una secuencia lineal de numeros
# Empieza en 0, acaba en 20, en pasos de 2
# (similar a la funcion interna range())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Crea array de cinco valores igualmente espaciados entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Crea un arreglo de 3x3 con valores aleatorios
# distribuidos de manera uniforma entre 0 y 1
np.random.random((3, 3))

array([[0.38334202, 0.8364935 , 0.75344588],
       [0.49743426, 0.02222792, 0.18910781],
       [0.47994283, 0.52085061, 0.17049464]])

In [10]:
# Crea un arreglo de 3x3 con valores aleatorios
# distribuidos de manera normal con media 0 y desviacion estandard 1
np.random.normal(0, 1, (3, 3))

array([[-1.70145262,  1.08614019,  0.69686007],
       [ 0.34403348, -0.53994747,  1.16725075],
       [-0.80490618,  0.873108  ,  0.03265976]])

In [11]:
# Crea array de 3x3 de numeros enterros aleatorios tomados del intervalo [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 6, 5],
       [8, 9, 5],
       [9, 9, 5]])

In [12]:
# Crea matrix identidad de 3x3 (arreglo cuyas entradas son todas cero excepto las diagonales)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Crea un array de tres enteros sin valores especificos
# Los valores se toman de lo que exista en esa localizacion de la memoria
np.empty(3)

array([1., 1., 1.])

#Basicos de NumPy: arreglos

Categorias de manipulaciones básicas de arreglos:

- *Atributos de arrays*
- *Indexado de arrays*
- *Rebanadas de arrays*
- *Reformado de arrays*
- *Union y separación de arrays*

## Atributos de Arrays

In [0]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [15]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [16]:
print("dtype:", x3.dtype)

dtype: int64


In [17]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Indexado de Arrays : Acceso a elementos individuales

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x1[0]

5

In [20]:
x1[4]

7

In [21]:
x1[-1]

9

In [22]:
x1[-2]

7

In [23]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [24]:
x2[0, 0]

3

In [25]:
x2[2, 0]

1

In [26]:
x2[2, -1]

7

In [27]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Rebanadas de Arrays: Accesa a partes (subarrays)

``` python
x[start:stop:step]
```

### Uni-dimensionales

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [31]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [32]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [33]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [35]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensionales

In [37]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [39]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [40]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Subarrays son vistas y no copias

- Es importante, y práctico, entender que las rebanadas de arrays son *vistas* del trozo y no *copias* del subarray

In [41]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


extraer un subarray de $2 \times 2$ de éste:

In [42]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Ahora si modificamos este subarray, el array original también cambia! Miren:

In [44]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [45]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


- Este comportamiento es de utilidad pues se pueden acceder y procesar partes de los arrays sin tener que hacer copias de ellos

### Creando copias de arrays

- En ocasiones será práctico crear copias explícitas de los datos
- Esto se hace con el método ``copy()``:

In [46]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


Si ahora modificamos este subarray, el original no cambia:

In [47]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [48]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reformado (reshaping) de Arrays

- Podemos cambiar la forma (reformar) de un array usando el método ``reshape``
Por ejemplo, si queremos los número del 1 al 9 en un array de $3 \times 3$, podemos hacer lo siguiente:

In [49]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [51]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [52]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [54]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

##  Concatenación y Separación de Arrays

- Es posible  combinar multiples arrays en uno
- Es posible separar un array a multiples arrays

### Concatenación de arrays

Concatenacion, o unión de dos arrays en NumPy, se puede hacer con ``np.concatenate``, ``np.vstack``, y ``np.hstack``.
``np.concatenate`` toma una tupla o lista de arrays como primer argumento:

In [55]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [56]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [0]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [58]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Separación de arrays

El opuesto a la concatenación es la sepación, implementada en las funciones ``np.split``, ``np.hsplit``, y ``np.vsplit``.  Para cada una de éstas podemos pasar una lista de índices en donde se quiere hacer la separación:

In [62]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


*N* puntos-de-separación, crean *N + 1* subarrays.

In [63]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
