<a href="https://colab.research.google.com/github/htapiagroup/introduccion-a-numpy-JosueJuarez/blob/master/Introducci%C3%B3n_a_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## Listas en Python 

Una lista es una estructura de datos que permite colectar objetos. 
Creamos una lista de enteros de la siguiente forma:

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

O una lista de caracteres de texto:

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

Gracias al tipado dinámico podemos crear listas heterogéneas:

In [7]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Arreglos de Tipo Fijo en Python

- En Python hay diferentes opciones para guardar datos en buffers de tipo fijo
- El modulo interno ``array`` (disponible a partir de Python 3.3) sirve para crear arreglos densos de tipo uniforme:

In [8]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Aquí ``'i'`` indica que las entradas son enteros.
- El objeto ``ndarray`` de la libreria NumPy  es mucho mas útil ya que implementa operaciones sobre los datos contenidos.
- Antes de explorar estas operaciones, veamos diversas maneras de crear arreglos de NumPy
- Comenzamos con la manera standard de importar NumPy, usando el alias ``np``:

## Crear Arreglos a partir de Listas de Python

Podemos usar ``np.array`` para crear arreglos a partir de listas:

In [9]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

- A diferencia de las lista en Python, NumPy está restringif a arreglos que contienen el mismo tipo de datos
- Si los tipos no coinciden NumPy trata de ajustar (*upcast*, emitir) si es posible
- En el siguiente ejemplo, los enteros se emiten a punto flotante:

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

- Podemos indicar el tipo de datos del arreglo explicitamente usando la palabra ``dtype``:

In [11]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

- A diferencia de las listas, los arreglos de NumPy pueden ser explicitamente multi-dimensionales
- A continuación, una forma de inicializar un arreglo multidimensional usando una lista de listas:

In [12]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

- Las listas interiores se toman como renglones del arreglo bidimensional resultante